### ISSUE TITLE
macOS target

### ISSUE THREAD

**Issue by glaszig** [arsonik/AKTransmission#1]
forked this repo and tried to add a target for macOS. carthage seems to build ok but when i `import AKTransmission` into my macOS project, it says the "no such module". i have the framework search path configured properly and the framework added as a dependency. any idea?

**Comment by glaszig** [comment]
nevermind. i'm just unable to handle xcode. might pr later.

**Comment by arsonik** [comment]
its probably because I havent made a target for Mac in the lib
